model:
  name: react_memory
  max_iterations: 5   # maximum iterations for agent
  max_retry: 5        # for LLM calling

tools:
  Finish:
    open: true
  GetTaskDescription:
    open: true
  GetRelationDefinition:
    open: true

train:
  if_train: false
  if_predict: true
  if_evaluate: true

data:
  type: re
  name: DuIE2.0
  language: zh
  num_samples: 20
  num_samples_index: 1000

llm:
  model_name: gpt-4-turbo-preview   # gpt-3.5-turbo-0125
  temperature: 0
  max_tokens: 4096

  use_cache: false    # for random
