import: base_config.yml
model:
  name: codekgc

train:
  if_train: false
  if_predict: true
  if_evaluate: true

data:
  type: re
  name: DuIE2.0

llm:
  model_name: gpt-4-turbo-preview
  # model_name: gpt-3.5-turbo-instruct
  temperature: 0
  # max_tokens: 4096
  max_tokens: 1000
  use_cache: true
