import: base_config.yml
model:
  name: zsl_cot

train:
  if_predict: false
  if_evaluate: true

data:
  type: re
  name: DuIE2.0
  num_samples: 5

llm:
  model_name: gpt-4-turbo-preview
  temperature: 0
  max_tokens: 4096

  use_cache: true
  # cache_key: zsl_cot_v0.1
  